#ifndef PROJETGSI_FLAGS_H
#define PROJETGSI_FLAGS_H

#define ERROR_IN_CMD_LINE -1
#define ERROR_SCHED_AFFINITY -2
#define ERROR_OPEN_STREAM -3
#define ERROR_WRONG_JSON_STRUCTURE -4

#endif //PROJETGSI_FLAGS_H
